version: "3"

services:
  swagger:
    image: sys/docs
    build: ./docs
    ports:
      - 8080
    environment:
      BASE_URL: /docs
      SWAGGER_JSON: /api.yaml
    volumes:
      - ./docs/api.yaml:/api.yaml
    networks:
      - bridge
  nginx:
    build: ./nginx
    image: sys/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - bridge
    depends_on:
      - swagger
      - user
      - course
      - log
  nats:
    image: nats-streaming:alpine
    command:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "nats_clus",
      ]
    ports:
      - 4222
      - 8222
    networks:
      - bridge
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - bridge
  user:
    image: sys/user
    build:
      context: ./src/user
      args:
        - NODE_ENV=dev
      secrets:
        - npmrc
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - MONGO_URI=${MONGO_URI_USER_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=nats-cli_user
      - NATS_CLUSTER_ID=nats_clus
      - REDIS_URI=redis://redis:6379
    networks:
      - bridge
    depends_on:
      - nats
      - redis
  course:
    image: sys/course
    build:
      context: ./src/course
      args:
        - NODE_ENV=dev
      secrets:
        - npmrc
    ports:
      - 3001:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - MONGO_URI=${MONGO_URI_COURSE_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=nats-cli_course
      - NATS_CLUSTER_ID=nats_clus
    volumes:
      - ./src/course/uploads:/usr/uploads:rw
    networks:
      - bridge
    depends_on:
      - nats
  log:
    image: sys/log
    build:
      context: ./src/log
      args:
        - NODE_ENV=dev
      secrets:
        - npmrc
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - MONGO_URI=${MONGO_URI_LOG_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=nats-cli_log
      - NATS_CLUSTER_ID=nats_clus
    networks:
      - bridge
    depends_on:
      - nats
  landing:
    image: sys/landing
    build:
      context: ./src/landing
    ports:
      - 3003:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - MONGO_URI=${MONGO_URI_LANDING_SRV}
    networks:
      - bridge

secrets:
  npmrc:
    file: .npmrc

networks:
  bridge:
