### get roles
GET http://localhost:8000/roles HTTP/1.1

### create roles
POST http://localhost:8000/roles HTTP/1.1
Content-Type: application/json

{
  "name": "student",
  "level": 2,
  "permission_ids": ["649fe3106fbfb0595aec3880"]
}

### delete roles
DELETE http://localhost:8000/roles/649fe3b96fbfb0595aec3881 HTTP/1.1