export const MNG_CODE = {
  GET_PERM: "GET_PERM",
  NEW_PERM: "NEW_PERM",
  MOD_PERM: "MOD_PERM",
  DEL_PERM: "DEL_PERM",

  GET_ROLE: "GET_ROLE",
  NEW_ROLE: "NEW_ROLE",
  MOD_ROLE: "MOD_ROLE",
  DEL_ROLE: "DEL_ROLE",

  GET_USER: "GET_USER",
  NEW_USER: "NEW_USER",
  MOD_USER: "MOD_USER",
  DEL_USER: "DEL_USER",
};

export const LOG_CODE = {
  GET_LOG: "GET_LOG",
};

export const APP_CODE = {
  COURSE: "COURSE",
};

export const COURSE_CODE = {
  GET_UNIT: "GET_UNIT",
  NEW_UNIT: "NEW_UNIT",
  MOD_UNIT: "MOD_UNIT",
  DEL_UNIT: "DEL_UNIT",

  GET_CLASS: "GET_CLASS",
  NEW_CLASS: "NEW_CLASS",
  MOD_CLASS: "MOD_CLASS",
  DEL_CLASS: "DEL_CLASS",

  GET_COURSE: "GET_COURSE",
  NEW_COURSE: "NEW_COURSE",
  MOD_COURSE: "MOD_COURSE",
  DEL_COURSE: "DEL_COURSE",
};
